# Model Configuration
model:
  model_id: "HuggingFaceTB/SmolVLM2-500M-Video-Instruct"
  lora_adapter_path: "" # "/media/vishal/workspace/projects/AlignVLM/checkpoints/localized_narratives_200k/checkpoint-5200"
  use_align_connector: false
  is_train: false

# Dataset Configuration
dataset:
  path: ""
  id: "lmms-lab/COCO-Caption"
  cache_dir: "/media/vishal/datasets/hf_cache/"
  few_shot:
    enabled: false
    num_examples: 2

# Evaluation Configuration
eval:
  metric: "Cider score"
  batch_size: 4
  num_workers: 4
  pin_memory: true
  cider_tokenizer_path: "/media/vishal/workspace/projects/AlignVLM"